export const ADD_SEARCH = 'ADD_SEARCH'
export const ADD_SEARCH_REQUEST = 'ADD_SEARCH_REQUEST'
export const REMOVE_REQUEST = 'REMOVE_REQUEST'
export const MOVE_SEARCH_TO_TOP_AND_MAKE_REQUEST =
	'MOVE_SEARCH_TO_TOP_AND_MAKE_REQUEST'
